### ISSUE TITLE
is there anything like ZeroBlog

### ISSUE THREAD

**Issue by dontspamm** [ipfs/notes#115]
does IPFS have a tool like [ZeroBlog](https://github.com/HelloZeroNet/ZeroBlog) ? if not is there any way to fork it and use it for IPFS ?

**Comment by noffle** [comment]
I don't think anyone has created a blogging "platform" yet.

However, IPFS is already very good at hosting static directory structures, such as static HTML websites. [Here's](https://ipfs.io/ipfs/QmdPtC3T7Kcu9iJg6hYzLBWR5XCDcYMY7HV685E3kH3EcS/2015/09/15/hosting-a-website-on-ipfs/) an article on how to do this using the `ipfs` CLI tool.

**Comment by Kubuxu** [comment]
Also see https://github.com/ipfs/notes/issues/90

**Comment by dontspamm** [comment]
huge is not safe to be installed, it triggers a warning on Ubuntu

**Comment by shaman** [comment]
I've just started work on experimental IPFS blogging platform https://uberpen.org 
Any feedback is welcome on [GitHub](https://github.com/uberpen)
