### ISSUE TITLE
PubSub Scalability

### ISSUE THREAD

**Issue by noffle** [ipfs/notes#119]
This issue is to discuss the different approaches to building a pubsub architecture that will be able to achieve high levels of scale (read: millions of members, 1:many and many:many, high rate of messages, low latency), as well as the trade-offs (eventually consistent, availability, consistency, partition tolerance).

**Comment by noffle** [comment]
cc @haadcode @whyrusleeping @nginnever @jbenet

**Comment by diasdavid** [comment]
There was an already started discussion at https://github.com/ipfs/notes/issues/64. Can we close this issue and use that one, so that everyone that was involved, remains involved?
