### ISSUE TITLE
Twitter Cards for ipfs.io URLs

### ISSUE THREAD

**Issue by Mithgol** [ipfs/notes#120]
[Twitter Cards](https://dev.twitter.com/cards/overview) appear in microblog entries on Twitter when some other web site is referenced by a hyperlink. Twitter automatically follows a hyperlink and provides a summary based on some metadata from meta tags in the head of the designated web page. Twitter understands its own set of meta tags and also Facebook's [Open Graph](https://en.wikipedia.org/wiki/Facebook_Platform#Open_Graph_protocol) metadata.

This feature has to be explicitly enabled beforehand for each of the referenced web sites.

I suppose that someone of IPFS's developers should enable Twitter Cards for `ipfs.io` and let Twitter fetch metadata and display cards for IPFS-hosted web pages.

**Comment by RichardLitt** [comment]
I can do that. It's not hard, and I've done this 100 times before. Good call. 

@jbenet go ahead? developer time: 20 minutes.

**Comment by dignifiedquire** [comment]
Sounds like a really good idea to me :)

**Comment by jbenet** [comment]
Yeah go for it.

Make sure it works similar to medium and other user-generated-content
sites-- because anyone can display any cards (can violate terms and could
get whole domain banned, unless it's clear to them it's user generated)

**Comment by Mithgol** [comment]
![(WHAT HAPPEN?)](https://cloud.githubusercontent.com/assets/1088720/13879228/69e374ce-ed27-11e5-99b6-01eadb41c156.png)

**Comment by dignifiedquire** [comment]
@RichardLitt did this ever happen?

**Comment by RichardLitt** [comment]
@dignifiedquire Doesn't look like it. Will do.

**Comment by Mithgol** [comment]
This comment is a quarterly nudge.

**Comment by VictorBjelkholm** [comment]
@Mithgol maybe I'm missing something but this is up to the user itself, and works already as far as I can see. I tried with adding the following source:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>ipfs.io Twitter Card</title>
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:site" content="@ipfs" />
	<meta name="twitter:title" content="This is a card served from ipfs.io" />
	<meta name="twitter:description" content="View it on ipfs.io" />
	<meta name="twitter:image" content="https://ipfs.io/ipfs/QmUqYxTvnGTfqhuo68cVzxQ8ENzLd99PKagTnjuAaQDanx" />
</head>
<body>
	<h1>Share this on Twitter</h1>
	<p>https://github.com/ipfs/notes/issues/120</p>
</body>
</html>
```

Which results to https://ipfs.io/ipfs/QmahHnjhqDGKU89L6RhJvzkPt5dsc8oUq6paKzzoC76grR that I shared on twitter and it looks like this:

![](https://ipfs.io/ipfs/QmTTRdKfC7ib9ymXi9YvRrFa5WqCfgBbeqdPsLLBeFjz95)
Tweet: https://twitter.com/VictorBjelkholm/status/795592963145527296

Am I misunderstanding what this is about?

**Comment by Mithgol** [comment]
Thanks for bringing this to my attention.

Yes, Twitter Cards work on IPFS as intended.

Additionally, now I notice that the announcement at https://twittercommunity.com/t/automatic-cards-whitelisting/34207 does in fact say that Twitter Cards do not require approval (through the validator) after 2015-03-01, yet I've opened #120 (a year later) based on an outdated assumption of the opposite.

I am now closing this issue because it is clearly revealed to be solely based on a bit of my ignorance.

**Comment by VictorBjelkholm** [comment]
Ah, I see. Thanks @Mithgol for the clarification!

**Comment by RichardLitt** [comment]
Ha! Alright, thank you @Mithgol and thank you @VictorBjelkholm for figuring this out. :)
