### ISSUE TITLE
Tool: iphost / ipmirror / ipserve

### ISSUE THREAD

**Issue by noffle** [ipfs/notes#122]
#### What is it?

A small tool that operates in a manner analogous to a traditional static http file server. The core motivation is having a static file hosting metaphor for sysadmins who don't want to / need to grok IPFS' model.

It does essentially what “ipfs daemon + ipfs add + ipfs pin” can do, but with a UX analogous to setting up a traditional static HTTP server; this self-contained tool provides a trivial metaphor for simple-web users who want to ensure availability of files.
#### Advantages
- Small self-contained binary (includes its own IPFS Node)
- Self-contained metaphor -- acts like a traditional http server /wo needing to understand IPFS’ model
- All of the other IPFS niceties (deduplication, cheap LAN replication, free CDN’ing if others on the IPFS network have the files)

**Comment by lgierth** [comment]
Could be similar to `python -m SimpleHTTPServer`, while watch'ing the directory, adding changed files.

```
> iphost
creating /tmp/ipfs-repo-for-pwd
mounting /path/to/pwd at /ipns/Qmfoobar
iphost listening on http://127.0.0.1:8080
watching /path/to/pwd for changes
```

**Comment by lgierth** [comment]
And maybe rather call it `ipserve`? host is a veeery generic term in the context of IPFS.

**Comment by noffle** [comment]
Yes, agreed 100%. :heart:

**Comment by daviddias** [comment]
Really worth looking into @agentofuser's ipfs-deploy tool https://github.com/agentofuser/ipfs-deploy, I believe it fits this usecase and works extremely well!

**Comment by daviddias** [comment]
Additionally, https://fleek.co/ took it to the next level and made website hosting super easy!
