### ISSUE TITLE
"Multi" Org + Protocol Suite Name

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#135]
We need an org name for the "multi" protocol family:

- multihash
- multiaddr
- multikey
- multicodec
- multistream
- multibase

The possibilities that come to mind:

- multiprotocols
- multis
- multicodes
- multisuite
- multiprotos
- multiformats

This word should fit these sentences:

- Multihash and Multiaddr are both [ part of ] ________ .
- [The] _________ [ is / are ] a collection of formats or protocols that use efficient self description to provide interoperability and cryptographic agility.
- [The] ________  [ is / are ] so useful.
- If you design it as a ______ system, then you're not locked in.
- ________ system
- `https://github.com/______`
- `https://_______.io`

Try saying them out loud.

**Comment by jbenet** [comment]
cc @diasdavid @lgierth @whyrusleeping @dignifiedquire @RichardLitt @nicola @steballien @kubuxu

**Comment by whyrusleeping** [comment]
'multis' is a nice option.

**Comment by nicola** [comment]
I am all for multiprotocols (if you want to be fancy, multiwg, wg is for working group)

**Comment by Stebalien** [comment]
I also like multiprotocols.

Also, "multis":

![](https://upload.wikimedia.org/wikipedia/commons/e/ee/1AKC_Maltese_Dog_Show_2011.jpg)

**Comment by nicola** [comment]
multispecs

**Comment by RichardLitt** [comment]
Multiprotocols
Multispecs
Multis

In order of preference.

**Comment by lgierth** [comment]
I like multispecs

**Comment by lgierth** [comment]
- Multihash and Multiaddr are both [ part of ] *multispecs*.
- [The] *multispecs* [ is / are ] a collection of formats or protocols that use efficient self description to provide interoperability and cryptographic agility.
- [The] *multispecs* [ is / are ] so useful.
- If you design it as a *multispecs* system, then you're not locked in.
- *multispecs* system
- https://github.com/multispecs
- https://multispecs.io

None of these really work with "multis" :)

**Comment by condiosluzverde** [comment]
Fabric

----
james mcfarland
james@jamesmcfarland.com
www.jamesmcfarland.com

**Comment by condiosluzverde** [comment]
Hashfabric

----
james mcfarland
james@jamesmcfarland.com
www.jamesmcfarland.com

**Comment by Kubuxu** [comment]
If we are listing ideas: `multispace`.

**Comment by diasdavid** [comment]
`Self Describable Protocols`, with acronym `SDP`. 

"Multihash and Multiaddr are both SDPs"

**Comment by nicola** [comment]
https://en.wikipedia.org/wiki/Session_Description_Protocol :(

**Comment by pbronez** [comment]
Multicols = Multiple Protocols

 - Multihash and Multiaddr are both Multicols.
 - Multicols is a collection of formats or protocols that use efficient self description to provide interoperability and cryptographic agility.
 - Multicols are so useful.
 - If you design it as a Multicols system, then you're not locked in.
 - Multicols system
 - https://github.com/multicols
 - https://multicols.io

**Comment by haadcode** [comment]
How many tickles do you need to make a specification laugh?
Multickles

I'll get me coat...

**Comment by jbenet** [comment]
I think so far these are liked the most:
- multiprotocols (5 s)
- multispecs (3 s)
- multis  (2 s)

---

multispecs is growing on me. 
- @lgierth's plugging into examples makes it very clear that it can be used in sentences where "protocol" and "format" are there without much issue. 
- short, sounds nice. ("multiprotocols" is more clear, but it's a mouthful. and 5 syllables)

--- 

- people dont like "multiformats" ? (4 syllables)

**Comment by dignifiedquire** [comment]
I really like multicols with multispecs in second place

**Comment by RichardLitt** [comment]
Multicols sounds to me like multicolumns. I'm not sure it's a good portmanteau.

**Comment by diasdavid** [comment]
My favourite is still `SDP`, but second favourite is multispecs

**Comment by jbenet** [comment]
@diasdavid i like SDP too, but clashes. And i think "Self Describing Protocols" should include more than these small formats-- ideally stuff around pulling the code and running it in a VM. Stuff that builds on these, but that brings closer to the stuff [alan kay](http://www.vpri.org/pdf/tr2015004_cuneiform.pdf) and others have worked on (see references in Alan's paper).

**Comment by jbenet** [comment]
- I think "multispecs" is more popular with the people in this thread.
- I think let's abandon "multiprotocols", it's way too long and hard to say.

Some more plugs for "multiformats"
- I think "multiformats" is easier to say than "multispecs"
- "format" is more accurate. a "format" is also a spec, but specifically describes encodings or representations (these so far all involve encodings and representations).
- after trying it for a bit on people, "multiformat" seems to do better at evoking what these things are. "multispecs" seems to general.

I will be at https://www.w3.org/2016/04/blockchain-workshop/ and try both on people and see how they go.

**Comment by dignifiedquire** [comment]
:+1: for multiformats

**Comment by lgierth** [comment]
multiformats is just fine!

**Comment by jbenet** [comment]
I tried both on people, multiformats seemed to give that set of people a better feel. multispecs was too vague. I think we should go for it. I'll give a few days for anyone to raise concerns

**Comment by jbenet** [comment]
- @diasdavid got https://github.com/multiformats
- @jbenet got https://github.com/multispecs

The main thing preventing me from settling on "multiformats" is that it _is hard to read_ in writing:

---

- multihash and multiaddr are both multiformats.
- If you design it as a multiformat system, then you're not locked in.
- multihash and multiaddr are both multispecs.
- If you design it as a multispecs system, then you're not locked in.

**Comment by jbenet** [comment]
- Maybe multiformats could be _camel-capitalized_: MultiFormats
- Maybe multiformats could be _abbreviatged_: MF

- multihash and multiaddr are both MultiFormats.
- If you design it as a MultiFormat system, then you're not locked in.
- multihash and multiaddr are both MFs.
- If you design it as an MF system, then you're not locked in.

**Comment by jbenet** [comment]
- Maybe multiformats could be _camel-capitalized_: MultiFormats
- Maybe multiformats could be _abbreviatged_: MF

eg

- multihash and multiaddr are both MultiFormats.
- If you design it as a MultiFormat system, then you're not locked in.
- multihash and multiaddr are both MFs.
- If you design it as an MF system, then you're not locked in.

Capitalizing may mean:
- people start writing: MultiHash, MultiAddr, MultiCodec, MultiStream.

which may be ok, and may even be better in prose.

Thoughts?

**Comment by lgierth** [comment]
> The main thing preventing me from settling on "multiformats" is that it is hard to read in writing:

Because of the "tif" in the middle? I find it okay to read.

> people start writing: MultiHash, MultiAddr, MultiCodec, MultiStream

Then we may want to update type names in go and javascript.

**Comment by jbenet** [comment]
> Then we may want to update type names in go and javascript.

indeed. im not sure. :S

**Comment by RichardLitt** [comment]
I believe that this can be closed now. Please refer to github.com/multiformats.
