### ISSUE TITLE
Idea: IPDB - Database

### ISSUE THREAD

**Issue by mkg20001** [ipfs/notes#150]
(moved from https://github.com/ipfs/ipfs/issues/192)
IPDB Idea:
- local: a database on the client
- public: a database in the network
- Peer: a database shared with a specific Peer
  Blocks:
- public-database
  Contains links to databases and signed change/add requests from Nodes
- database
  Contains links to tables
- table
  Contains Blobs (links to others hashes/files) or Strings/Integers/...

Any App could use /ipdb/APP/local or public to load entrys and execute querys

```
/ipdb/APP/public/PEER <-- public database of PEER
/ipdb/APP/PEER <-- shared with PEER
/ipdb/APP/local <-- local database
```

After a table is changed a new table Block is created (or something like "changelogs") by the node and a change request for the public database is created.

An alternative would be a mongoDB like structure instead of tables, which would be easier.
both tables and (whatever they are called in mongoDB) in parralel would be also an idea.

Feel free to comment suggestions, it's just a idea.
Sorry for my bad english.

**Comment by TimDaub** [comment]
@mkg20001 We're working on https://ipdb.foundation/ here.
If you have questions, feel free to ask.

**Comment by harlantwood** [comment]
See also https://github.com/ipfs/notes/issues/133

**Comment by bitcard** [comment]
mark

**Comment by bertrandfalguiere** [comment]
@bitcard 

> mark

Please stop commenting "mark" on issues. If you want to be notified in the future, just activate the notifications for the issue with the bell. If you wabt to save the page, just put them as favorite in your browser. You can even organise it in a folder and sync it with your phone.

Commenting for no reason spams us we notifications and emails that are quite annoying. Please stop.

**Comment by aschmahmann** [comment]
@bitcard you've been asked to stop a couple times already. You've been given a temporary ban for a few days.

I'm glad you're interested in following the work going on in the community and contributing to the IPFS and libp2p ecosystems. However, these GitHub issues are a shared space that needs to be respected. If you've got any questions on how to appropriately follow work you can just start a discussion thread on discuss.ipfs.io or ask on the IPFS Matrix/IRC channels.
