### ISSUE TITLE
Interop requirement - spdy / http2

### ISSUE THREAD

**Issue by diasdavid** [ipfs/notes#16]
Opening this discussion on a issue, so that we have a log, as it has been a recurring topic for a while now :)

For interop purposes between implementations, it has been discussed several times to replace `yamux` for `spdy`, so other implementations can have access to a standard stream multiplexing library. However,  most implementations for spdy or http2 are not there yet and pretty much every single one of them doesn't offer a streamable io interface, with the exception of `spdystream` by Docker, however, @whyrusleeping and @jbenet found some deadlock scenarios that still need to be solved/merged by the Docker team.

So, I guess we have to figure out if http2/spdy is the way and if so, will we invest resources on making our own implementation/supporting a current open source one?

**Comment by whyrusleeping** [comment]
does the spdystream implementation by docker even interop correctly with one of the node implementations? I feel like that would be a good thing to test before we go much farther down that road.

**Comment by diasdavid** [comment]
For logging purposes:

It was discussed and reviewed again and `spdy` will be it :)

As for the spdystream implementation in Node.js, had a quick chat today with Indutny on IRC:
```
13:59 <daviddias> hey indutny , how is it going ? 
13:59 <indutny> good good
13:59 <indutny> how are you?
14:00 <daviddias> doing good, thank you. Still on the track of making spdystream
14:01 <indutny> yeah
14:01 <indutny> I think node-spdy will give you the primitives
14:02 <indutny> just wait a bit :)
14:05 <daviddias> definitely, that was where I started. But there were some bits I didn't understand completely, so I started hacking from scratch spdy to make sure I understood all of the nuances, but hell, so there is so many bits to it. You did an awesome job on node-spdy
14:06 <indutny> heh
14:06 <indutny> daviddias: node-spdy is going to become much better now
14:13 <daviddias> indutny nice! So what is missing? I happy to help :) 
14:14 <indutny> daviddias: lots of stuff, but I am still in the process of reshuffling code
14:14 <indutny> not sure if any help is possible atm
14:14 <indutny> but thank you!
```
The refactor should take about 2 weeks (ref: https://github.com/indutny/node-spdy/issues/208)

**Comment by diasdavid** [comment]
We have it now :)

**Comment by CMCDragonkai** [comment]
Which version of SPDY is ipfs using? The wikipedia says that the latest version is version 4.0.

**Comment by diasdavid** [comment]
We use 3.1
