### ISSUE TITLE
Suggestion Blog admin panel

### ISSUE THREAD

**Issue by Snarkly** [ipfs/notes#163]
Non-coders will never use IPFS Blog if they have to code stuff into it. The blog needs an admin panel like wordpress for non-coders. I've shown ZeroNet to multiple people who can't code and they all said they wouldn't use it for the same reason, it has no admin panel for the blog. Please DON'T follow in ZeroNet's footsteps, create an admin panel for IPFS Blog.

**Comment by hsanjuan** [comment]
I am closing as there are several endeavors to make web publishing on IPFS easy. i.e. https://terminal.co/  so this has been addressed to a extent.
