### ISSUE TITLE
Collab with/support the people putting IIIF on IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/notes#170]
The work to put IIIF on IPFS (ie. [go-iiif](https://thisisaaronland.github.io/go-iiif/)) could open the gates to all the big cultural institutions ([British Library, Bibliothèque nationale de France, the Getty, all the big universities...](http://iiif.io/community/)) storing and serving all their image collections from IPFS. That would be huge for IPFS. 

Some of his work:
- https://github.com/thisisaaronland/go-iiif
- https://github.com/atomotic/go-iiif-docker

People
- @edsilv
- @thisisaaronland
- @atomotic

I had a conversation with @edsilv on the Internet Archive Slack: https://gist.github.com/flyingzumwalt/02fbf076fbe778b55c66ae3d6bef8927

@diasdavid this is relevant to your [presentation at the Web Archiving Conference](https://github.com/protocol/event-management/issues/23).  Ed mentioned it in the slack conversation.

**Comment by flyingzumwalt** [comment]
And check this out - @edsilv is [serving 3D models from IPFS](http://universalviewer.io/examples/?manifest=https%3A%2F%2Fipfs.io%2Fipfs%2FQmPXKbC96wb6zuUhd8m2HDoovZUqi3gFHbbL9W8vAEQX8a%2For_7694_1595.json&locale=en-GB#?c=0&m=0&s=0&cv=0)

**Comment by flyingzumwalt** [comment]
Question for IIIF people working with IPFS (@edsilv, @thisisaaronland, @atomotic, @anarchivist, etc): What can we help with? What info should we put out in the world that would be useful for you? Example: If @dignifiedquire gives a lightning talk at the IIIF meeting at the Hague this month, what message would be most important for him to convey?

**Comment by edsilv** [comment]
cc @aeschylus

**Comment by thisisaaronland** [comment]
In so far as `go-iiif` is concerned it's probably just a question of implementing one/both of the `source` and `cache` interfaces to speak IPFS:

https://github.com/thisisaaronland/go-iiif/blob/master/source/source.go#L8-L10
https://github.com/thisisaaronland/go-iiif/blob/master/cache/cache.go#L7-L12

**Comment by flyingzumwalt** [comment]
@thisisaaronland is there any information, encouragement or support we can provide that would encourage this implementation, or make it easier for you to implement it?

**Comment by edsilv** [comment]
IPFS could be a nice fit for annotation use cases: https://twitter.com/edsilv/status/773413548756242432

**Comment by thisisaaronland** [comment]
@flyingzumwalt – it's still morning here so I could be missing something but looking at go-ipfs it's not clear where/what I would plug in to a source/cache handler.

**Comment by edsilv** [comment]
Perhaps something about ipfs-cluster would be good. A roadmap towards enabling libraries to share infrastructure.

**Comment by flyingzumwalt** [comment]
For people who aren't familiar with IIIF, you here are some reference materials about IIIF
* About IIIF http://iiif.io/about/
* Technical Details about the 4 APIS (Image, Presentation, Search, Authentication): http://iiif.io/technical-details/
* The IIIF Presentation API http://iiif.io/api/presentation/2.1/ -- that's just their API for presentation.
* Another useful reference from @anarchivist's workshop at Hydra Connect: 
[Google Doc on IIIF and Data Modeling
](https://docs.google.com/document/d/1SUR21xKpM-ea8GEWSUWwgBGfwPshYjhoDsOFC0vBREQ/edit#heading=h.cbnfzn71dg9o)

**Comment by edsilv** [comment]
@flyingzumwalt @thisisaaronland I have a demo of IIIF 'level 0' image tiles being loaded from IPFS here: 

http://universalviewer.io/examples/?manifest=https%3A%2F%2Fipfs.io%2Fipfs%2FQmYomyCpT1vKNovYvTjAStYq31JoaH8xdivjmWcDj5mpM1

I used a python script to generate these: https://gist.github.com/edsilv/97759a93cb7c5f0fedb8178fee5e1dd3

Could it also be done with go-iiif's `iiif-tile-seed`?

**Comment by edsilv** [comment]
You would certainly want to talk about the legal and security aspects of running an IPFS node. A key question would be "can people put nasty things on my servers".

**Comment by edsilv** [comment]
Also worth mentioning? https://github.com/ipfs/archives

**Comment by flyingzumwalt** [comment]
Yeah. Let's close this issue. I think the goal was achieved. Some great demos, example code and new libraries came out of this collaboration.
