### ISSUE TITLE
Daemon slave mode

### ISSUE THREAD

**Issue by magik6k** [ipfs/notes#187]
Running multiple nodes multiple virtual machines on a single box/low-end (IoT) devices/multiple devices in fast LAN wastes sometimes limited resources(mostly RAM).

It would be nice to be able to start daemon is sort of slave/low resource mode, which would just forward API calls to master daemon. Slave configuration could be dove via config, daemon start parameter, local dns/hosts entry like `ipfs.local`, or by combination of them.

**Comment by Kubuxu** [comment]
It is possible to use `--api` argument to ipfs. You could create alias or wrapping script that would do it.

**Comment by diasdavid** [comment]
@magik6k I believe you got your question answer. If you have more questions on this topic, please open a topic on `discuss.ipfs.io` as this repo is used for discussions on research topics or implementations.
