### ISSUE TITLE
jid for IPLD - IPLD CLI explorer

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#194]
Would love to see something like https://github.com/simeji/jid to explore ipfs/ipld

**Comment by diasdavid** [comment]
@alanshaw is building this! \o/

Check it out at https://www.youtube.com/watch?v=AgjSBT3RQvg
and code at https://github.com/tableflip/ipld-explorer-cli/issues

**Comment by alanshaw** [comment]
Feedback welcome! @ipld/contributors?

**Comment by lidel** [comment]
@Mr0grog  visual explorer is on the roadmap for new WebUI, currently gathering ideas/inspiration in:

- Design: IPLD Explorer  https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/11

**Comment by diasdavid** [comment]
MOAR Updates from @alanshaw  https://twitter.com/_alanshaw/status/1034055822270193670

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1211152/44662246-7e983080-aa0d-11e8-9b67-f25c0222ebac.png">

**Comment by diasdavid** [comment]
Also, from the one and only @olizilla, the visual version!

https://twitter.com/olizilla/status/1024701525250195458  https://explore.ipld.io/#/explore
<img width="595" alt="image" src="https://user-images.githubusercontent.com/1211152/44662332-cd45ca80-aa0d-11e8-869a-8823498c5ac7.png">
