### ISSUE TITLE
Garbage collection management in IPFS

### ISSUE THREAD

**Issue by satyamakgec** [ipfs/notes#232]
Hi folks , is their any way or commands for gc management , I am building the application whose data would store on Ipfs, will it get deleted when those data can't be used over a long time as auto calling of garbage collection in java .

**Comment by hsanjuan** [comment]
`ipfs repo gc`?

**Comment by diasdavid** [comment]
@satyamakgec did @hsanjuan answered help you? If not, please consider reopening the question on `discuss.ipfs.io` where you can get more help. `ipfs/notes` repo is used for long discussions about research or implementation topics.
