### ISSUE TITLE
What is the main identification field of an ipfs node 

### ISSUE THREAD

**Issue by satyamakgec** [ipfs/notes#233]
How do I differentiate the ipfs node and what are the access requirement of an ipfs node and I have one more question is it possible to access the data from different node and uploaded by the different node .  Is their any way to run multiple ipfs node simultaneously on a system and all are access by the same access point as local host:5001/webui with the parameter of the node identification field.

Thanks , please help me out to solve this issue

**Comment by lidel** [comment]
The main identifier of ipfs node is `"ID"` returned by ` http://127.0.0.1:5001/api/v0/id`

For multiple node setups check [IPFS Cluster](https://github.com/ipfs/ipfs-cluster/#ipfs-cluster) ([they just announced call for early testers](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ipfs-users/_oAi-e0gUj8/eW-eahgvBQAJ)). Not sure if this is what you are looking for, but it provides one `/api/v0/` for all cluster members and means to synchronize pin data between all members.

**Comment by lgierth** [comment]
I think this is sufficiently answered, please reopen in the ipfs/faq repo if you still have questions.
