### ISSUE TITLE
Wishes

### ISSUE THREAD

**Issue by udatny** [ipfs/notes#235]
From a nobodys perspective my clear answer for a future cid standard is, whatever you do, dont make me dependend on a registration (or requirement to be part of a limited enumeration), as in v1 where you have a enum like cid (eth, btc, git, whatever major format) .

So, i prefer;

- to get as much (verified) information from outside about the data in a cid (such as size and type) - before fetching it. So a verification approach as in the bitcoin protocol (transaction verification) for the cid itself would be great. Info that one can rely on the provided info in the cid

- freedom of adding any content

- open / distributed registry for types 

Have a great day

**Comment by hsanjuan** [comment]
This is what exists. The multicodec table is open for everyone to propose types, but you can always use whatever without submitting it if that's what you really want. And of course there is freedom to add any content.
