### ISSUE TITLE
feature request: add a `/relay/ls` protocol to swarm that yields open connections from a peer

### ISSUE THREAD

**Issue by dryajov** [ipfs/notes#237]
We need a way to list remote peers active connections.

In addition, here are a couple more points to consider:

- What other useful information can be returned? 
- What additional commands or subcommands can be added alongside `ls`?

@diasdavid @dignifiedquire @whyrusleeping @lgierth

**Comment by whyrusleeping** [comment]
You might want to clarify the title as we do have an ls comand: `ipfs ls`

**Comment by diasdavid** [comment]
`multistream ls` is only the listing of the protocols supported by a node. I believe you were looking to propose a `/relay/ls`, updated the title of the issue accordingly.

**Comment by dryajov** [comment]
thanks @diasdavid!

**Comment by dryajov** [comment]
@diasdavid On that note, should it be `/relay/ls`, I thought this was not to be relay related anymore. Should it be more general purpose like `/libp2p/peers/ls`?

@whyrusleeping @lgierth?

**Comment by diasdavid** [comment]
No feelings on the name of the protocol yet :) `/relay/ls` is just a good name right now because it was where this proposal came from.

**Comment by diasdavid** [comment]
@dryajov I believe that I've seen this proposal in multiple shapes and in multiple places. Confirm if https://github.com/libp2p/specs/issues already has it and if not open it there.
