### ISSUE TITLE
Is there a place for documentation issues?

### ISSUE THREAD

**Issue by MatrixManAtYrService** [ipfs/notes#246]
I'm working through the examples at https://ipfs.io/docs/examples/ If I notice that the docs don't seem to match the software, would you like me to create an issue?  If so, where?

Here's the sort of thing I'm talking about:

> Based on the first part of [Dags and Blocks and Objects (oh my!)](https://ipfs.io/ipfs/QmNZiPk974vDsPmQii3YbrMKfi12KTSNM7XMiYyiea4VYZ/example#/ipfs/QmRFTtbyEp3UaT67ByYW299Suw7HKKnWK6NJMdNFzDjYdX/data/readme.md) it would seem that if a file is big enough, `ipfs ls <hash>` should show the blocks that it consists of.  In my experience, this doesn't happen.  If the hash doesn't point to a directory, the error: `Error: merkledag node was not a directory or shard` appears.

**Comment by whyrusleeping** [comment]
The examples are all based out of https://github.com/ipfs/examples

Issues for that should be filed there.

**Comment by MatrixManAtYrService** [comment]
Ok, thanks!
