### ISSUE TITLE
IPFS Through a proxy 

### ISSUE THREAD

**Issue by nezzard** [ipfs/notes#247]
Hi all, i have bad ip, but have vds with socks5 proxy. I need to run daemon on windows through  socks5  with login and password, how to do that?

**Comment by whyrusleeping** [comment]
Hey @nezzard, could you move this question to https://discuss.ipfs.io/ ? Thats a better place for this to get a solid answer

**Comment by diasdavid** [comment]
@nezzard closing this one, please follow @whyrusleeping suggestion and open the same question in `discuss.ipfs.io`
