### ISSUE TITLE
Decide on how to disambiguate IPLD pathing from IPFS pathing

### ISSUE THREAD

**Issue by Stebalien** [ipfs/notes#248]
Currently, the IPFS daemon plays it fast-and-loose with pathing and uses the CID (whether or not the object is stored as a protobuf) to decide on whether to path through it as an IPFS directory tree or an IPLD object.

Instead, we may want to consider using a `/ipld/...` prefix. We *definitely* should not be disambiguating based on the CID as the object encoding should have no bearing on how we path through it once we've decoded it.

**Comment by diasdavid** [comment]
I feel this Q should go into a discussion on https://github.com/ipld/specs. Nevertheless, I agree with the `/ipld` pathing, I believe @whyrusleeping does too.

**Comment by Stebalien** [comment]
Turns out we already have such a discussion: https://github.com/ipld/specs/issues/8
