### ISSUE TITLE
IPFS large data

### ISSUE THREAD

**Issue by telehubqt** [ipfs/notes#253]
How would one implement a large data transfer (lets say a video) via WebRTC star interface on the browser. The one problem is that this would have to be some kind of streaming, so the sending nodes will have to split the data into chunks right? and the browser node will have to pump this data to the player.. is there any example or an idea how this can be implemented?

Or, if its not a stream, it will be impossible to store it in a single data structure before being able to play it.

Edit: There is an interesting protocol called PPSPP which seems that might be compatible with ipfs, but there is nothing on this yet (https://tools.ietf.org/html/rfc7574)
Regards

**Comment by VictorBjelkholm** [comment]
There is a in-progress example for js-ipfs for how to do video streaming via the help of hlsjs-ipfs-loader which uses the HLS protocol. You can check out the current info and demo here: https://github.com/ipfs/js-ipfs/pull/947/files

**Comment by daviddias** [comment]
Hi @telehubqt! Seems your question got answered. If you are still working on this, consider opening future questions at https://discuss.ipfs.io. Cheers!
