### ISSUE TITLE
P2P CDN M.Sc Thesis

### ISSUE THREAD

**Issue by johnytiago** [ipfs/notes#267]
Hello everyone!

My name João Tiago and I'm a grad Student completing my master’s degree at [Instituto Superior Técnico, University of Lisbon](http://tecnico.ulisboa.pt/). I’m also a member of the development team of the [SINFO conference](https://sinfo.org/).

I’m super interested in learning more on Grid Computing and CDNs and my goal is to improve the Content Addressed fabric to give it properties that is not only available but it also moves to where it needs to be. I'm looking into things like caching, p2p load balancing, sharding and recovery of data.

Although I'm still at the beginning of my quest, I want to start contributing as soon as I can to the IPFS project while I still do the literature review and state of the art research. I work with [Luis Veiga](http://www.gsd.inesc-id.pt/~lveiga) and [David Dias](https://daviddias.me), both my M.Sc advisors.

My current timeline is the following:

- A first checkpoint on January 5th - Delivery of the _Project Proposal_. A document which identifies the problem I am attempting to solve, also the architecture of the solution I designed, inspired by the literature that I read.
- Second and final checkpoint in October - Full thesis delivery, after having implemented the proposed solution and gathered results.

If you have pointers, things for me to read, to contribute, people to talk to and other hints, I'm all ears! I’d love to meet the people working on these type technologies and hopefully get more people to work on the project as well.

Thanks!

**Comment by hsanjuan** [comment]
I hope you delivered the thesis!
