### ISSUE TITLE
DClaims  MSc Thesis - Distributed and Verifiable Claims with IPFS

### ISSUE THREAD

**Issue by joaosantos15** [ipfs/notes#268]
Hello, 

I'm João and I'm a grad student from the [University of Lisbon](https://tecnico.ulisboa.pt/en). I've been researching Blockchain tech, IPFS and Web of Trust in order to find alternatives to today's data monopolies, silos and lack of interoperability between organizations. 

My M.Sc Thesis work is focused on creating a functional solution to achieve a distributed platform for verifiable claims that entities and organizations can use to certify other entities, I call it Hypercerts. I'm working with  [Nuno Santos](http://www.gsd.inesc-id.pt/%7Ensantos/), from the University of Lisbon and [David Dias](https://github.com/diasdavid), from Protocol Labs, both my advisors for this project. 

Hypercerts' goals are:
- Develop a system to improve the verification of published news.
- Improve the [Blockcerts](http://www.blockcerts.org)' iniciative to Reduce Issuer hosted data dependence and improve revocation capabilities of blockchain issued certificates of accomplishment. I've to thank [Kim Hamilton Duffy](https://github.com/kimdhamilton) from [Learning Machine](http://learningmachine.com/) who has been providing me with a lot of insight and review for how to improve Blockcerts with this new system..

I've been participating the [Rebooting the Web of Trust](https://github.com/weboftrustinfo) and Blockcerts  projects and recentrly subscribed to the  [Verifiable Claims](https://w3c-ccg.github.io) working group.

Last week, I had the opportunity to attend Rebooting The Web of Trust's workshop (Oct 3-5 in Boston) where I met a lot of amazing people and grew my knowledge and interest in _decentralized identifiers_ (DIDs) and _self-sovereign identity_.

I've delivered the first part of my Thesis in June, [Hypercerts Project Proposal](https://github.com/joaosantos15/hypercerts/blob/master/Hypercerts_project.pdf) and now I'm working on the system, integration and collecting results to be delivered on April 2018. I am hoping that my deliverables include a proposal for different uses of Verifiable Claims, news verification and certification of accomplishments, accompanied by working demos of these two use cases. 

Currently, I am actively working on the certification of accomplishments and IPFS is a big part of that effort. I found @jonnycrunch's [presentation of IPID on the last all hands](https://youtu.be/iYD6eV4s280?t=2m12s), thank you for sharing that update, I found it really interesting for my work as DIDs are going to play an important role.

I really enjoy working with the open source community and do my research in the open. If you are interested in any of the stuff I just mentioned or if you have links to share (talks, papers, etc), I appreciate them.

Thank your for the amazing community you built and that continues to grow. :smile:

**Comment by diasdavid** [comment]
# Update

@joaosantos15 shared an update on the project at the last IPFS Lisbon Meetup. You can see it here:

[<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1211152/35243416-a1f1941e-ff71-11e7-83f5-7fda57ccbc93.png">](https://www.youtube.com/watch?v=4oIvWldzT4o)

**Comment by meiqimichelle** [comment]
Heeeyyyy I heard @joaosantos15 recently defended this thesis to great result. WAY TO GO @joaosantos15 !!!! 🎉 🎉 🎉 🎉 🎉

**Comment by pgte** [comment]
Congratulations @joaosantos15!!!

**Comment by joaosantos15** [comment]
Thank you @meiqimichelle @pgte ! Yes, it's true, I presented it about a week ago and it went really well. @diasdavid was one of my advisors (along with @nuno-santos) and a member of the jury, so congratulations to them as well!! :)

I'll leave some links here, in case you want to learn more about DClaims:
* [Main GitHub Repo](https://github.com/inesc-id/dclaims-pm) (with links to the other repos)
* [Thesis document](https://github.com/inesc-id/dclaims-pm/blob/master/thesis-project-doc) (the long explanation)
* [Extended abstract](https://github.com/inesc-id/dclaims-pm/blob/master/thesis-review/ExtendedAbstract_DClaims_JoaoSantos.pdf) (the short explanation)

We have submitted a paper for the 2018 Annual Computer Security Applications Conference ([ACSAC34](https://www.acsac.org/2018/)). As soon as the paper is made public, I'll share it here!

The original post I made on this issue does not really represent the scope of the final work. We shifted towards a censorship resistant web annotations platform. 

IPFS is big part of DClaims, as it offers a lot of desirable censorship resistant properties. I am extremely thankful to the entire team (PL and the entire open-source community) for creating and maitaining the IPFS project.

**Comment by daviddias** [comment]
Closing this thread as the work as been concluded. Keep rocking the DWeb 🤘🏽

**Comment by jesseclay** [comment]
Congrats @joaosantos15!!

**Comment by jsoares** [comment]
Great work @joaosantos15 and congrats on the SAC pub!

**Comment by joaosantos15** [comment]
Thanks @jsoares and @jesseclay! Yeah, it was a really nice week for DClaims:
⭐️ A 3 page version of the paper was accepted on [SAC2020](http://www.sigapp.org/sac/sac2020/) . 
⭐️ The the [extended version (published on arXiv.org)](https://arxiv.org/pdf/1912.03388.pdf), was selected as paper of the week on the 38th issue of [zkCapital's newsletter](https://zkcapital.substack.com).

This was only possible thanks to @nuno-santos 's work on this 🚀
