### ISSUE TITLE
ipget tool

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#27]
We need an `ipget` tool. a `wget` replacement. Super basic. essentially `ipfs get`.

let's keep prototyping this tool with the usage + examples

``` sh
> ipget
Usage: ipget <ipfs-path>
       ipget <ipfs-path> -o <local-path>
       ipget <ipfs-path> (-a | --api) <addr>
       ipget <ipfs-path> [--mdns] [--solarnet] [--bootstrap <list>]
       ipget <ipfs-path> [ (-t | --transports) <protos> ]


Options:

  -o, --output <local-path>   output to local path
  -t, --transports <protos>   toggle transports (tcp, utp, udt, ble, aud)
  -a, --api <addr>            delegate to node api at given address
  --mdns                      enable mdns discovery (default: true)
  --public                    use the public ipfs network for bootstrap (default: true)
  --bootstrap <file>          use custom bootstrap list

# shows a progress bar
> ipget QmbKYWCyTQWjUjwhS45uQGWQcMHaXJT81UVzPxqfY4uc7T
14.75 MB / 19.91 MB [=====================>----------] 74.09 %

# defaults to using `dirname` as output
> ipget /ipfs/QmbKYWCyTQWjUjwhS45uQGWQcMHaXJT81UVzPxqfY4uc7T/go1.4.2.src
> ls
go1.4.2.src

# can override output with -o and --output
> ipget /ipfs/QmbKYWCyTQWjUjwhS45uQGWQcMHaXJT81UVzPxqfY4uc7T/go1.4.2.src -o go
> ls
go

# can use a custom bootstrap list. (implies --public=false)
> ipfs bootstrap >list
> ipget $path --boostrap list

# public (on by default) toggles use of public network bootstrap nodes.
> ipfs bootstrap >list
> ipget $path --solarnet=false --mdns

# use only specified transports
> ipget $path -t utp,ble
```

Features:
- SHOULD have ephermal mode (create node on every run).
- MAY use ipfs-shell to delegate to another node (this is tricky to get right)
- SHOULD sniff + connect to localhost nodes first
- SHOULD have a bootstrap list option
- SHOULD use mdns
- SHOULD have progress bar
- MAY allow toggling specific transports

UX:
- as simple, nice, and trustworthy as `wget`

tagging people that may be interested in making this: @rht @cryptix @wking @whyrusleeping @jbenet
@lgierth

**Comment by cryptix** [comment]
Not sure whats the deeper idea here. Do you want to remove 'ipfs get' ?

**Comment by rht** [comment]
* SHOULD have download resumes/partials for robustness? (~ byte range in http header)
e.g. downloading huge data (e.g. LHC raw/derived data, though currently it is not so much, http://opendata.cern.ch/record/328/files/atlas-higgs-challenge-2014-v2.csv.gz) at 99% and then suddenly dc.

IMO, UX should reflect the actual structure underneath. ipfs ~ transport protocol + file system (+ git?). How is this like wget/scp/cp/ln, and how does this deviate from wget/scp/cp/ln?

@cryptix one use case: gx needs to download packages directly without having ipfs daemon in the background. One reason: thin client has less dependencies and so easier to package/disseminate. Maybe like 'git fetch' is an alias to git-fetch, 'ipfs get' is an alias to ipget?

**Comment by jbenet** [comment]
> Maybe like 'git fetch' is an alias to git-fetch, 'ipfs get' is an alias to ipget?

:+1: yeah, i think that can work well. the only caveat is that it should be an alias, but should specify to use the proper ipfs repo (instead of `ipget` using its own ephemeral node, or own repo, etc)

**Comment by jbenet** [comment]
maybe `ipget` can optimistically understand fsrepo (flatfs) format and use blocks from a local repo if it is there. 

also, i wish that:

```sh
> ipget QmbKYWCyTQWjUjwhS45uQGWQcMHaXJT81UVzPxqfY4uc7T # slow, first time download.
> ipget QmbKYWCyTQWjUjwhS45uQGWQcMHaXJT81UVzPxqfY4uc7T # fast, already cached locally
```
not sure yet how to do that o/ without either: (a) writing directly to local repo, (b) relying on local ipfs daemon running, (c) having its own, separate repo.

--- 

one of the reasons i want ipget is to be able to use ipfs to download ipfs updates, so i want `ipget` to work even if your local (main) ipfs distribution is hosed.

**Comment by noffle** [comment]
Took a first stab at this: https://github.com/noffle/ipget

![ipget](http://ipfs.pics/pic.php?id=QmTQowQ75tKvVSXHGHrGyHBT3P7V9d6zPsvtETLM5wJCZg)

It's **very** rough and needs a lot of love to get to the place where it's a pleasant tool to use, but it fires up its own node and does work in the strictest sense of the word.

**Comment by rht** [comment]
@noffle It's very clean though (next is porting the rest of `ipfs get` functionalities?).
gx needs to run "without" the daemon as an option as well.

**Comment by hsanjuan** [comment]
This was shipped: https://github.com/ipfs/ipget
