### ISSUE TITLE
Most links to the CONTRIBUTING.md are broken

### ISSUE THREAD

**Issue by nloomans** [ipfs/notes#282]
Hey, I know this place is not for reporting 'issues', but i'm not sure where else to report it.

Most links to the CONTRIBUTING.md are broken, an example is https://github.com/ipfs/ipfs#project-and-community. If you click on contribute to IPFS gif you will see a 404. This is because it links to contributing.md instead of to CONTRIBUTING.md.

**Comment by Stebalien** [comment]
May be best to simply revert https://github.com/ipfs/community/ff38ebf65448353587e938e61ca36829fbecc8b4 as this rename affects *all* of our projects (all READMEs point to this document).

**Comment by VictorBjelkholm** [comment]
Yeah, agree with the revert. This is linked on so many places (some Google Docs we've made public also links this).
