### ISSUE TITLE
Sockets for communication between peers

### ISSUE THREAD

**Issue by thelesbianguy** [ipfs/notes#290]
Sockets for communication between peers

**Comment by Stebalien** [comment]
You mean between external applications (using IPFS)? We actually support this, checkout the `ipfs p2p` command.

**Comment by thelesbianguy** [comment]
Cannot find. Can you give me the link to it?

**Comment by Stebalien** [comment]
Fair enough: https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-p2p ("More documentation" is literally listed as a todo...).

As that documentation isn't very helpful:

On both nodes, you'll need to enable the feature (it's currently experimental):

```sh
> ipfs config --json Experimental.Libp2pStreamMounting true
> ... restart ipfs ...
```

On one of your IPFS nodes (NODEA)b, you'll need to register a listener. First, start your application and have it listen on `YOUR_PORT`. Then, run:

```sh
> ipfs p2p listener open /my/custom/protocol/name /ip4/127.0.0.1/tcp/YOUR_PORT
```

This will configure IPFS to listen for new streams speaking the protocol `/my/custom/protocol/name` and, for each new stream, proxy the stream to `127.0.0.1:YOUR_PORT`.

Next, on the the other IPFS node, run

```sh
> ipfs p2p stream dial $NODEA_ID /my/custom/protocol/name /ip4/127.0.0.1/tcp/SOME_PORT
```

And, connect your application to `127.0.0.1:SOME_PORT`. The connection will be proxied through to the listener on the other node.

**Comment by Stebalien** [comment]
FYI, I've improved that documentation in: https://github.com/ipfs/go-ipfs/pull/4894

**Comment by thelesbianguy** [comment]
thanks a lot
