### ISSUE TITLE
Problems with adding files over 15MB with progress handler

### ISSUE THREAD

**Issue by salamantos** [ipfs/notes#293]
I tried to create progress bar to my file uploading. I used this code:
`let progress_func_video = function (len) {
  console.log("video progress:", len);
};
ipfs.files.add(files_video, {progress: progress_func_video}, (err, result) => {...}`

When I upload 1MB files, it's ok, but on 30MB filse I got this error in Chrome:
`POST https://site.com:81/api/v0/add?progress=true&stream-channels=true net::ERR_INCOMPLETE_CHUNKED_ENCODING`
`Uncaught (in promise) TypeError: network error
    at new exports.IncomingMessage (response.js?99b5:67)
    at module.exports.ClientRequest._connect (request.js?af32:259)
    at eval (request.js?af32:157)`

How to fix it?

**Comment by lidel** [comment]
Hi, this repository is used for Research and Idea Discussions, so you may want to close this and re-open in https://github.com/ipfs/js-ipfs-api (which I assume you are using).  
FYSA it may be related to known issues with uploading big files via `js-ipfs-api` in Chrome, eg.  https://github.com/ipfs/js-ipfs-api/issues/654

**Comment by salamantos** [comment]
Yes, my bad..
