### ISSUE TITLE
The New Internet

### ISSUE THREAD

**Issue by novusabeo** [ipfs/notes#297]
Hi,

I wanted to share with you, IPFS, an idea that I think can only be utilized on IPFS/Filecoin. I am familiar with blockstacks and using it and dig it — also with Dtube and other apps implementing IPFS but i feel there is something a little missing. I know all of this with blockchain is pretty new and new ideas and ways to use it are just beginning to take shape into the new world. But I have an idea relating to the distributed internet that I have yet to see anywhere and I think is really happenin. I am prettu unsatisfied with steemit as a “decentralized” content platform. I realize this is in part due to the fact that content is prioritized in a way that is not in my hands as a piece of it. I think this may be because steemit is more appealing to tranditional means of content deployment and social networking. But what its lacking does not embrace the full power and potential of a distributed system or mesh like IPFS embraces. With a distributed system the potential for exploration becomes limitless. Without content set on specific servers as central access points the need for prioritization of content based on “whats hot” and so forth becomes pointless. Also - steemit is currently limited in its scope and design and not really a full umbrella of what is possible in relation to content — thus you have two separate linked systems (dtube and steemit) that diminish UX. In terms of UX think of a platform using the essence and ideas of IPFS but that can search and find all content in the entire everything deployed upon it - videos, art, info, businesses, identities, people, etc. Should those entities themselves choose to interact with it. With IPFS the potential becomes that we can create essentially an online open wilderness of everything that you are free to explore like the universe of No Mans Sky where nothing is specifically prioritized unless you yourself choose to search for it categorically or choose to prioritize it upon a criteria. What I am saying is this. Create a platform that is a blank sheet of white paper where anything can be put upon it. And then i the user can explore and add to it completely as I choose to. This is essentially the difference right now between facebook and instagram for me in terms of what I like. With Facebook content is prioritized based on preset criteria of amount of likes, what the system thinks I’m interested in, etc. Fuck that! Let me choose what I want to see. Let me roam the wilderness and see what i like. And much like instagram let me choose who i want to follow and then lay it all out before my eyes not based on arbritrary systems but again based on how I want to see it laid out. If i want to see what you think I like — let me choose that. If i want to see what my friends have posted recently — let me choose that. If i want to see only pictures of french fries from business that sell them in a specific town in france — let me choose that. Dont show me content based on advertising and likes and shit like that that has in some way been manipulated (even algorithmically manipulated). I want to be able to roam this wilderness as i see fit, interact with what i want to as i see fit, explore as i see fit. This is a truly decentralized, distributed web. Steemit is no good - it is “curating” content. This makes for an unsettling experience. Show me it all and then let me decide what i want to see based on what criteria i choose. If i want to see advertising or popular things, i will choose it. This will allow for entities to develop and succeed in a natural way based on the reality of their usability - giving them real life identity and distinction online. This becomes possible with the mesh and the distributed web. This kind of exploration will give the system its actual function and usability. This is what needs to go down. With IPFS and distribution i realize that at first, a system like this will not be able to stand on its own in a fully distributed format. So at first use filecoin and storage systems to host the content in this way and then as more people use it, the less the need is for large storage systems as bigger specific points in the mesh. The beauty of this is that as it grows, the more people use it, the more efficient and global it becomes. This is true decentralization — not the stuff that is mostly happening with blockchain and “distributed ledger” nowadays. IPFS is the only thing that can accomplish this. Blockstacks is ok, but still centralized in the way that it is aimed more at apps than the whole entire universe of content. But on this idea there is room for everything - businesses apps, media, artists, IP, private information - all distributed and cryptographically sealed and distributed as IPFS objects in pieces that the millions of devices using it are essentially creating. Think of this - I go on the Cosmic web using the Inter Planetary File System and can browse everything. Or I can go to my friends identity page and see their content they have shared with the cosmos or specific content they have showed to me. Or I can query the whole cosmos for french fries and french fries will come back to me as everything in an unprioritized (thus uncentralized) way. Businesses with french fries, pictures of french fries, poems with french fries, information about french fries, publically available gps coordinates of french fries, pornographic french fries. I can browse all of this if i want. I can then choose to narrow it if i want. Maybe i dont want to see pornographic french fries. Hopefully the content uploader when uploading this tagged it as pornographic. I click hide pornographic content. If they didnt click that it is still there. I can then click on the pornographic french fries and say “this is pornographic” and it will hide if my hide pornographic search criteria is clicked. This is also where the magic happens. Maybe it isnt reallt pornographic but i think it is. So that object is marked by my identity as such. But maybe 30 other people dont think it is. So for them it isnt. Or maybe 100 people agree it is pornographic - so they all click that and it creates a tally tied to thay IPFS object. Once it receives a co siderable consensus it can be decidedly sent to the uploader that this content has been determined as such and you did not click that when uploading so do you accept the new criteria based on the tally of 100? In this way content can be filtered by the community itself and the entire internet in this way will be based on direct human trust and discernment not some central body that is dictating the filtration. For me - i trust that most people will tag the content they upload themselves because otherwise it will just look dumb. And because in this distributed web it is a wilderness so you are going to share what is important not try to be a dick and sway for likes or whatever because it is not based on that. I was also thinking that the self categorization of your content should be expanded heavily. Like on Dtube it says “is this nsfw?” When uploading. Lets make that more decentralized (different people have different definitions of what that means). Instead have many different options for filtration tied to that object that people can choose when uploading alongside the hastag system. For instance have a whole selection of things like - is this erotic? Does this show nudity? Is this pornographic? Does this have political content? Etc. This way people when searching can filter out specific types of content themselves based on what they want to see. This way people can use this to both explore content, search specifically, or search generally by way of filtration they decide on. This can be used for everything. Businesses can be put on this - someone can search for “food near me” and have their cryptographically sealed gps locale be queried to the whole distributed web and matched with entities that have also cryptographically sealed and shared their coordinates (businesses). Also - no bullshit advertising or prioritization of content based on how much adwords you have. Let that be based on what the searcher wants to see. If i want to search for “popular food near me” i will. Plus i can search for “food near me”, explore some and see how they are and what people are saying. This will create a system where reviews are actually tied to operating identities in the wilderness - thus establishing actual trust on both ends! - instead of assailing yelpers harassing unnecessarily with no actual identity that they can just erase and create another yelp account the next day if they need to. Its like, cmon, everyone and their grandma is a fking google “local guide”. 

So yes! The interplanetary file system needs a cosmos to operate in. So I give you the cosmic web! A place to explore and find what you want how you want to. You are after all, a piece of the cosmos and your place in it is real and contributes to. This cosmic web is how the web should be. 

-John Morrow

**Comment by lidel** [comment]
Hi @novusabeo, thank you for taking time for sharing your thoughts!

There are interesting ideas in this wall of text (content curation in decentralized web etc), but as you can see github comments do  not work well for the long form  :)

Perhaps you could close this issue, reformat the text and repost it on our comminity forum at http://discuss.ipfs.io ?
(If you splt the text  into proper paragraphs and add some section headers it will be easier for people to reason what topics are touched by the text)

**Comment by Illasera** [comment]
**JEEZ**, formatting, I can't even read this.

This comment was not meant as a feedback but as a pointer to the OP to learn formatting & brevity.
