### ISSUE TITLE
Consider the use of other cryptogaphic primitives (ed25519 for example)

### ISSUE THREAD

**Issue by mildred** [ipfs/notes#307]
It would be nice if we had the choice of which cryptography primitive we use for objects. Specifically, I would prefer using [ed25519](http://ed25519.cr.yp.to/) which is an elliptic curve algorithm that was not approved by NIST. But its security is equivalent to ~3000-bit RSA while having much shorter keys and being way faster.

It would also be a great feature when we'll have to upgrade to stronger primitives in the future.

**Comment by Stebalien** [comment]
We now have support for ed25519 and friends.

**Comment by daviddias** [comment]
@Stebalien fully? Even for dialing?

**Comment by Stebalien** [comment]
The only thing remaining is enabling creating ed25519 keys: https://github.com/ipfs/go-ipfs/issues/3625.
