### ISSUE TITLE
Open Archives on IPFS

### ISSUE THREAD

**Issue by davidar** [ipfs/notes#31]
IPFS seems like a great solution for distributing open-access scientific publications. There are a number of open-access archives that would be beneficial to mirror on the IPFS network, to ensure these publications remain available in the event the original host disappears (which happens all too frequently). A few suggestions for organisations that we could approach (feel free to add more in the comments):

- CiteSeerX (@davidar and @jbenet currently discussing IPFS mirroring with the CSX team)
- arXiv (probably only the subset of CC-licensed papers) - see http://arxiv.org/help/bulk_data
- PLOS
- [CORE](http://core.ac.uk/)
- conference proceedings (NIPS, UAI, ACL, AAAI, ICML, etc) - see http://dblp.uni-trier.de/
- JMLR
- Pascal network eprints (currently offline, but might be able to obtain a backup copy)
- DSpace@MIT
- Project Euclid
- a variety of OAI-accessible eprint archives, such as those listed on http://opendoar.org
- [Jaynes' (un)published works](http://bayes.wustl.edu/)
- Google/Microsoft Research publications?
- [Orchid eprints](http://www.orchid.ac.uk/eprints/)

**Comment by davidar** [comment]
A little tangentially, it would also be good to have a general mirror service (e.g. https://mirrorservice.org ) connected to ipfs. This could also help with jbenet/random-ideas#19

**Comment by jbenet** [comment]
@davidar yeah that would be nice!

**Comment by davidar** [comment]
I've harvested the metadata from arXiv's [OAI endpoint](http://gateway.ipfs.io/ipfs/QmdKjhpvnWYbqps2hFJJNSBSwDv4NKQyPnxkAFWmAuHiuD/arxiv-oai.html). The raw dump is available in the same directory as that file, but I haven't finished seeding it properly (~2GB), so don't try to access it quite yet. The bits we're probably most interested in are the [CC-licensed articles](http://gateway.ipfs.io/ipfs/QmdKjhpvnWYbqps2hFJJNSBSwDv4NKQyPnxkAFWmAuHiuD/cc.txt.gz) --- there seems to be about 15-20k of them all up. Still need to:

- [ ] extract the CC-licensed paper IDs and mirror the associated files
- [ ] process the raw metadata stream into a nicer format
- [ ] automate the process of [syncing OAI](https://github.com/davidar/oai-sync) repos to IPFS
- [ ] apply the same process to the huge list of other public OAI repos before they disappear

**Comment by davidar** [comment]
Alternatively, [BASE](http://www.base-search.net/) have already [indexed](http://www.base-search.net/about/en/about_sources_date_dn.php) a whole bunch of OAI repos (including stats about open-access articles), and seem to provide OAI/rsync [access](http://oai.base-search.net/) to their data upon request.

**Comment by jbenet** [comment]
All this LGTM! As we go, we may want to document a basic "mirroring to ipfs protocol" to throw into a readme and let other users help out.

> lternatively, BASE have already indexed a whole bunch of OAI repos (including stats about open-access articles), and seem to provide OAI/rsync access to their data upon request.

Sweet, let's rsync it over to sirius or pollux. @davidar can you give me an ssh key to give access to?

**Comment by davidar** [comment]
@jbenet Sure, once I sort out the details, I'll try to make it so it's relatively easy for anyone to sync to ipfs (or incrementally update existing ones). SSH pubkeys [here](https://github.com/davidar.keys)

**Comment by davidar** [comment]
Just came across [Paperity](http://paperity.org/), which also looks very cool.

**Comment by lgierth** [comment]
@davidar could you mail me your SSH key to my-github-handle@ipfs.io? Preferrably ed25519 instead of RSA: https://stribika.github.io/2015/01/04/secure-secure-shell.html

**Comment by lgierth** [comment]
Oh sorry, didn't realize you already posted them. But still could you get me an ed25519 key? :)

**Comment by jbenet** [comment]
@lgierth is there a crypto issue with RSA? Aside from a preference ed25519, RSA 2048+ is still known to be fine (AFAIK)

**Comment by lgierth** [comment]
There's no particular issue, I'm just gently pushing people in the right direction :) I'm fine with RSA.

> though we should just bump up

Exactly! :)

**Comment by lgierth** [comment]
@davidar to avoid confusion: I'll add your RSA key (which one btw?), but if you feel like migrating to ed25519, now's the time! :)

**Comment by davidar** [comment]
@lgierth Ok, I've migrated to ed25519 :)

**Comment by davidar** [comment]
Migrated to https://github.com/ipfs/archives
