### ISSUE TITLE
keys in kademlia

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#320]
@whyrusleeping and I were discussing keys in kademlia. There is an issue with using multihash values directly, as multihashes bias the first two bytes. this messes with the kademlia key space, because values hashes with, say, sha3 would be "really far away" from peer ids hashed with, say, sha2, according to kademlia's xor distance.

Atm, two solutions make sense:
1. DHTs (and routing systems in general) could project the IPFS multihash space into its own key space. e.g. re-hash all multihashes with the dht's own choice of hashfn (say, sha2 256). This ønly affects dht lookups. It has the drawback that the keys looked up on the dht are the hash of the keys of the objects/peer IDs, (i.e. different and potentially smaller hashes), but it solves the bias issue above. It's also nice in that the key space is uniform in a particular size.
2. Modify the XOR distance metric to reverse the XOR output before taking it as an int value. This puts the multihash bias at the least significant bits, ensuring hash values of one multihash function are distributed evenly along the values of another (as far as the xor distance metric is concerned). the sha3 values are no longer categorically "really far away".  this keeps the key lookups in the dht as the same multihash values, only changes dht implementation of the xor metric. (i'm not 100% sure this works, but seems right. please point out if this is broken).

(BTW, i'll add that comparing hash outputs of different sizes should pad zeroes _at the end_, not the front).

Atm leaning on 2, but want to be 100% sure it works before going fwd. we can do either for now and change it before first release.

**Comment by Stebalien** [comment]
We went with solution 1.

**Comment by Stebalien** [comment]
> ? Assuming you mean: if the dht uses sha256, and sha256 breaks, what then? -- yeah this is a problem in the dht, and the dht would need to move to a different hash function (which we built multihash to avoid!!), and thus why i don't like it.

Historical note: as far as I can tell, this isn't actually an issue. We're using sha256 as a pseudo-random function to distribute keys across the key space. Key _collisions_ don't matter because records are _stored_ by CID, peer ID, etc.
