### ISSUE TITLE
Hashing files with no identifiers can lead to bad behaviour.

### ISSUE THREAD

**Issue by Illasera** [ipfs/notes#345]
Not an issue but a debate we need to address
Since the files are hashed and identified as such, 
Wouldn't be easy for someone to send a data stream with malicious content
that we won't even have an indicator to what it could be? since its all hashed.

No domains, no MIME types, no extensions, We are pretty much working blindly here and expecting
the URL given to be safe, but it could be anything.

Should we discuss the issue and see how we can resolve it?

**Comment by daviddias** [comment]
Seems to me that the discussion reached a conclusion. Closing this one :) Reopen if necessary
