### ISSUE TITLE
OpenWRT archive

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#35]
I recently downloaded all of downloads.openwrt.org and will be re-hosting it on ipfs. this issue tracks discussion and progress.

**Comment by lgierth** [comment]
Yeah let's get that storage box :P

**Comment by kenCode-de** [comment]
sorry, i know this is a bit off-topic, but has anyone successfully installed ipfs on a newer raspi? i was thinking of moving my shared folder to the pi and keeping the pi plugged in to my openwrt router indefinitely. i am going to put the Smartcoins Wallet apk out there on ipfs for safe keeping and just need to see if this method is even possible or not as of yet... thanx for your time :)

**Comment by lgierth** [comment]
Yes thanks this is off-topic. go-ipfs runs fine on glibc-based linux on the raspi. Newer OpenWrt's come with musl instead of glibc, so you'll have to cross-compile go-ipfs with musl instead of glibc. We'll have prebuilt musl-based binaries on dist.ipfs.io in the future.

**Comment by nicopace** [comment]
@lgierth have you tried to compile ipfs on OpenWRT?
I saw that there is a way to add golang to the OpenWRT toolchain like this: https://mqmaker.com/doc/play-golang-on-openwrt/
but i don't have enougth knowledge to get to this
