### ISSUE TITLE
p2p file transfer for ~1KB files

### ISSUE THREAD

**Issue by klueq** [ipfs/notes#359]
What's the most efficient way to send 1KB of data from node A to node B?

I see two options:

1. Send it in a UDP message.
2. Node A uses `ipfs add`, sends the file hash to node B, which uses `ipfs get`.

How much overhead does the 2-nd option have?

**Comment by daviddias** [comment]
@klueq this issue would be better for our forum at https://discuss.ipfs.io. Closing it here, please reopen at https://discuss.ipfs.io/ if you would like to continue. Thank you!
