### ISSUE TITLE
npm module names

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#36]
- `go-ipfs` -- installer for go implementation
- `ipfs-api` -- api wrapper
- `ipfs` -- the node ipfs implementation
- `ipfs.js` -- browserified node-ipfs + ipfs browsing inside your regular http browser

**Comment by jbenet** [comment]
hey @ckeenan just saw https://www.npmjs.com/package/ipfs.js -- any chance we could use that module name? the `ipfs.js` thing we're making is gonna be pretty sweet, though it's a bit far off atm.

**Comment by ckeenan** [comment]
Yeah sure, no problem. It's open now

**Comment by jbenet** [comment]
thank you @ckeenan -- i squatted it for now: https://www.npmjs.com/package/ipfs.js
