### ISSUE TITLE
IPFS Demos

### ISSUE THREAD

**Issue by jbenet** [ipfs/notes#365]
The goal is to work towards a set of working demos.
- `ipfs` cli to `add cat ls` files. (done)
- mounted `/ipfs` that streams files on demand (needs dht + bitswap)
- mounted `/ipfs/ctrl/add-block` and `/ipfs/ctrl/add-file` which publish things
- mounted `/ipns` that resolves `/ipns/<name>` names
- mounted `~/Box` that versions, encrypts, publishes, + syncs files added
- http gateway at `http://ipfs.io/<ipfs-path>` that fetches blocks (POST to `http://ipfs.io/ctrl/add-{block, file}`)
- `ipfs.js` for in-webpage ipfs -- using WebRTC and fallback to http gateway
- IPFS browser extensions to fetch `ipfs://` or `http://ipfs.io/` links smartly.
- mount package manager registries (e.g. all npm packages installed at `/ipns/npmjs.org/package/<package>@<version>`)
- mount github (e.g. all github repos accessible at `/ipns/github.com/<username>/<repo>`)
- git interop (import git repos) 
- ipfs backed git (mount an IPFS backed `.git` repo)
- boot an OS from a hash

This is a good start. But suggest more below!

**Comment by daviddias** [comment]
If you happen to be looking for more cool stuff that has shipped over time, check out https://awesome.ipfs.io 🚀
