### ISSUE TITLE
Allow users to delete/modify things of IPLD

### ISSUE THREAD

**Issue by Jorropo** [ipfs/notes#368]
So just to be sure, IPLD is the things allowing you to link somethings under `/ipfs/Qm.../index.html` to a real document like `/ipfs/Qm...` ? So I'll use ipld name to describe this things (if I'm wrong pls tell me so I can correct it :smile: )

Currently I can't do any rm in ipfs.
So I doesn't looked all the docs but I'm pretty sure that IPLD emit some signed messages indicating wich file to reach. So why not add a timestamp to this messages so all client will only keep the latest one (because we don't need to know what was before, we just need to know now).
So if a user wanna change a file that will not really delete or remove the file, just override the pointer to this file.
We can also add a type wich can be Add or modify wich when receive change the pointer or if it not exist, create it.
And a remove type wich when receive remove the reference to the file.

Obviously only message with the right signature will be accepted to remove/override so only the right people can do the change.

If multiple events use the same timestamp they are all rejected, so that force user to use different timestamp.

The timestamp should be uint64 or varuint and use at least milliseconds but I think nanoseconds is better because 2 concurrent tasks may change 2 different object at same time.

I also understand the goal of keeping file longer as possible alive so we may can keep all remove/modify events and with an advanced option (maybe a params in url so it can be share) a way to go back in time getting latest events prior to this date.

***EDIT***
After some random walk on the doc I found that https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#mutable-file-system
And it have some files.mv or rm option so, is it exactly what I suggest ?
If yes why I can't do it using the mount option of go ipfs ?

**Comment by Stebalien** [comment]
You're describing something called IPNS. IPNS is, as you describe, a signed, timestamped, pointer to a file/directory. Basically,

1. IPLD is the underlying datastructure system we use for hash-linked content addressable data.
2. IPFS/UnixFS is the filesystem we build on-top of this datastructure system. `/ipfs/Qm.../path/to/file.txt` operates at the unixfs layer.
3. IPNS is a signed pointer to some path. The path is _usually_ an IPFS/IPLD path (`/ipld/Qm...`, `/ipfs/Qm...`).

So, to get mutability, we do something called copy-on-write. That is, we make the required changes to the IPFS directory and then update the IPNS pointer to point to the new directory.

>  And it have some files.mv or rm option so, is it exactly what I suggest ?

Pretty much, yes.

>  If yes why I can't do it using the mount option of go ipfs ?

`/ipns/local` *should* be a mutable, mountable filesystem (where updates are published to the network using IPNS). Unfortunately, this feature isn't quite as stable as it could be (although we have people actively working on it).

**Comment by Jorropo** [comment]
@Stebalien ok thx.
You help me a lot to understand ipfs better.
