### ISSUE TITLE
[Question] Estimated number of IPFS users?

### ISSUE THREAD

**Issue by DaniellMesquita** [ipfs/notes#371]

**Comment by Stebalien** [comment]
CC @momack2

**Comment by momack2** [comment]
ipfs/notes/ isn't the best place for questions and discussion. Moving this to [a discuss thread](https://discuss.ipfs.io/t/estimating-number-of-ipfs-users/4983).

**Comment by Stebalien** [comment]
Note: This _is_ the right place to discuss new ideas, proposals, etc.
