### ISSUE TITLE
I've found a website that use my node to share some illegal video, what should I do ?

### ISSUE THREAD

**Issue by Jorropo** [ipfs/notes#372]
I've found a website that use my ipfs gateway (https://jorropo.ovh/ipfs/) to share some illegal video, what should I do ?
I have ip of all people accessed to this file via my node and right now I shutded down my proxy (due to a bug in nginx blocking configuration state to only block this videos).
I will fix that and then totaly block these url, but should I report to any authority the ip of all these peoples ?

**Comment by Stebalien** [comment]
You should ask a lawyer (the EFF may be able to give you advice but I have no idea). Unfortunately, we can't provide legal advice.
