### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by lgierth** [ipfs/notes#38]
Please comment if you want a term added or improved (or do it yourself).

### Here we go

- **Random Walk**: querying the DHT for random keys, in order to discover new peers and fill gaps in keyspace
- **MFS**: mutable filesystem (see also: FUSE)
- **unixfs**: merkle-dag based data structures for representing unix files, directories, and symlinks

**Comment by MichaelMure** [comment]
maybe IPLD, IPNS, IPRS, cbor, starlog, starship, solarnet ?

**Comment by RichardLitt** [comment]
Added to the [ipfs/glossary](//github.com/ipfs/glossary) in https://github.com/ipfs/glossary/commit/5465d4aeca05eca8ec4dd42898fad3384e1d1e65 and https://github.com/ipfs/glossary/commit/956971b9fec6c2eb6a085031fe623bc1dac784a2. 

Please add more and contribute to that list!
