### ISSUE TITLE
Censorship resistance, especially in China

### ISSUE THREAD

**Issue by blurHY** [ipfs/notes#424]
In China, IPFS is unusable because of the GFW.
What does GFW do:
 - Block all default bootstrap nodes
 - Set up a node and start collecting ips to ban

What can we do to make it censorship-resistant ?

**Comment by Stebalien** [comment]
(moved to ipfs/notes as this is a discussion about the IPFS protocol itself)

@blurHY bootstrapping without relying on the default bootstrappers is slated for go-ipfs 0.6.0 (May-ish). However, that won't fix the problem of collecting IP addresses.

Unfortunately, it's prohibitively difficult to completely hide the fact that a computer is running an IPFS node without, e.g., tunneling all the traffic out of the country. I believe the best we can do is gain enough adoption of the underlying protocols such that blocking the entire protocol is infeasible.

**Comment by Ayms** [comment]
@blurHY if the question is for me, no, this is on hold, see the previous link

**Comment by blurHY** [comment]
Yeah, partly. 
To make ipfs resistant in China, we need obfuscating protocols, like v2ray, to break through GFW.
I don't know if your protocols can be resistant to GFW.

---
btw, i'm not working on this these months, and i won't use this identity in the future

**Comment by RubenKelevra** [comment]
This ticket is somewhat related...

https://github.com/ipfs/go-ipfs/issues/7066

**Comment by RubenKelevra** [comment]
This one is too, those nodes with a lot of connection points ARE probably the GFW. 

https://github.com/ipfs/go-ipfs/issues/7040

**Comment by jhonalino** [comment]
whats the point of calling this decentralization if it doesn't work in china?

**Comment by emugel** [comment]
"Inter-planetary", save for China...

**Comment by chompomonim** [comment]
> whats the point of calling this decentralization if it doesn't work in china?

Decentralised is not equal censorship resistant.

**Comment by anonmate** [comment]
I suggest anybody interested could look at using something like https://www.masq.ai – a decentralised multi-hop routing protocol that's shown to work through the GFW

**Comment by bertrandfalguiere** [comment]
> I suggest anybody interested could look at using something like https://www.masq.ai – a decentralised multi-hop routing protocol that's shown to work through the GFW

How is it better than Tor with a bridge?

**Comment by olanod** [comment]
Is it solved? if not why not keep it open?

**Comment by TheRook** [comment]
IPFS can be accessed over Tor and the Tor project is clearly taking this issue more seriously than IPFS:
https://support.torproject.org/censorship/connecting-from-china/

It would be good to see IPFS adopt similar infrastructure to keep the network from being censored. It seems IPFS has done the opposite with having IPFS censorship as a feature:  (https://twitter.com/peterktodd/status/653784515874299904)

**Comment by Ayms** [comment]
Surprised to see that this thread is still alive

IPFS over Tor? No it's not serious, I will not argue why again and gave up proposing [node-Tor](https://github.com/Ayms/node-Tor), which nobody understand

You might take a look at: [Deanonymizing quietly all of Tor](https://github.com/Ayms/Deanonymizing-quietly-all-of-Tor)

Not public but it might be that part of the attack is used by China, but not the complete one

**Comment by TheRook** [comment]
> Surprised to see that this thread is still alive
> 
> IPFS over Tor? No it's not serious, I will not argue why again and gave up proposing [node-Tor](https://github.com/Ayms/node-Tor), which nobody understand
> 
> You might take a look at: [Deanonymizing quietly all of Tor](https://github.com/Ayms/Deanonymizing-quietly-all-of-Tor)
> 
> Not public but it might be that part of the attack is used by China, but not the complete one

Have you actually used tor?  Serious question, because - would you willingly use tor if you had any choice?  Well over a billion people live in countries that have a great firewall like address filter.  Seeing as IPFS is built on Kad, i think Kad is the better p2p tool for this problem.

Tomorrow even more people will be censored, and Tor will be even less able to help them.

**Comment by Ayms** [comment]
You must be kidding for the first question: yes (and for example it's easy to add node-Tor nodes in the Tor network), second question: yes for standard uses, no if I risk my life (other link above...), look at node-Tor this is based on the use of the Tor protocol between IPFS/whatever nodes for examples and/or browsers not the Tor network even if this can be combined , this is very different and can bypass firewalls

**Comment by TheRook** [comment]
Tor is massively overkill - why force users over a tunnel to bypass a
denylist?   Also Tor is blocked - they have to use a bootstrap (
https://support.torproject.org/censorship/connecting-from-china/) - which
the same bootstrap could be used to bring nodes onto Kad without needing to
put all of that burden on Tor - which is already terrible at file transfer.

**Comment by Ayms** [comment]
Tunnel? denylist ? bootstrap ? Don't understand what you are talking about, let's stop here
