### ISSUE TITLE
DNS Providers

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/notes#53]
We might want something better than DigitalOcean. Right now, they're have all-or-nothing API keys, which means creating [dnslink-deploy](https://github.com/ipfs/dnslink-deploy) (which I also can't test, as I don't have the IPFS credentials, and arguably shouldn't). I think there are other reasons, but I can't strictly remember them at the moment. 

Cloudflare might work. There's this [really unhelpful list](https://en.wikipedia.org/wiki/List_of_managed_DNS_providers) on Wikipedia of managed DNS providers. Someone on Twitter suggested [OVH](https://twitter.com/OVH). ion on Twitter suggested PowerDNS on our own server. "Among other things, PowerDNS is nicer to configure than Bind, has a better security history to my knowledge and has a nice interface to delegate certain queries to code of your own."

Discuss?

**Comment by lidel** [comment]
3rd party:
Cloudflare provides a nice API, well documented at https://api.cloudflare.com

Self-hosted:
The most secure BIND alternative right now is [djbdns](https://en.wikipedia.org/wiki/Djbdns).
PowerDNS is also a good choice, for some use cases it may be easier to set up/migrate to (see  [this comment from PowerDNS maintainer](https://www.reddit.com/r/dns/comments/wrp9z/powerdns_vs_djbdns_thoughts/c5g63yt))

**Comment by daviddias** [comment]
We now use simple-dns :) Closing issue as `legacy`
