### ISSUE TITLE
Apparmor profile

### ISSUE THREAD

**Issue by vitzli** [ipfs/notes#62]
Simple apparmor profile for IPFS. Allows reads from `/srv/repos/` and `/srv/torrents`, allows r&w to `/home/*/download/`.

Here: [usr.local.bin.ipfs](https://gist.github.com/vitzli/ed63308a6bddf259d6f8). Change the name and path inside the profile if new name or path is required (default is `/usr/local/bin/ipfs`).
The profile assumes that `~/.ipfs/` directory exists, it must be created manually before executing `ipfs init` or ipfs will fail.

**Comment by hsanjuan** [comment]
This issue is old and I'd say in the wrong place (probably an apparmor profile should be distributed with go-ipfs?). I'll close it, though it'll remains discoverable through search engines. Thanks for sending it though!
