### ISSUE TITLE
ipfs levelDOWN module

### ISSUE THREAD

**Issue by daviddias** [ipfs/notes#72]
Node.js leveldb module was built in a way to support several storage drivers, from levelDB C++ bindings to level.js so that it can be used in the browser. 

![image](https://cloud.githubusercontent.com/assets/1211152/11353170/b41a012e-9238-11e5-9060-6d50f14a2d89.png)

http://leveldb.org/
https://github.com/Level/levelup/blob/master/README.md#leveldown

leveldown interface https://github.com/Level/abstract-leveldown

I'm thinking that it should be interesting to have a IPFS module that implements the same levelDOWN interface, so that all of the ecosystem that lives on top of levelUP (like even SQL datastores), can leverage IPFS as the data storage layer.

This will be also very interesting for all sorts of benchmarks

**Comment by ehd** [comment]
@diasdavid Pinging @grncdr. He did all kinds of silly things with ipfs and level abstractions I believe.

**Comment by jbenet** [comment]
+9001

**Comment by pgte** [comment]
Related: https://github.com/ipfs/notes/issues/244

**Comment by diasdavid** [comment]
@pgte this can be built without any notion of db sync'ing, in fact it would be interesting to create these primitives so that then the upper layer abstractions to levelDOWN would operate over this IPFS store and replace over time what exists on those layers to do distributed syncing, with IPFS primitives :)

**Comment by pgte** [comment]
@diasdavid yes, that's true, I hadn't thought of that. The data may only have local relevancy, but still be backed by IPFS. That's a good starting point, as we can start figuring out the IPLD structures before we become too concerned with syncing..

**Comment by pgte** [comment]
First take here: a database that only has local key-value structure, backed by IPFS:
https://github.com/pgte/ipfs-level

Next: sync, partly being discussed here: https://github.com/ipfs/notes/issues/244
