### ISSUE TITLE
IPFS Desktop Application using Electron

### ISSUE THREAD

**Issue by bcomnes** [ipfs/notes#8]
Per discussion earlier https://botbot.me/freenode/ipfs/2015-05-18/?msg=39538941&page=7

It would be great to run ipfs as a more traditional desktop app.  Here is a minimal set of ingredients to get that up and running:

- [x] Flesh out [node-ipfsd-ctl](https://github.com/ipfs/node-ipfsd-ctl)
- [x] Bundle prebuilt [npm-go-ipfs](https://www.npmjs.com/package/go-ipfs) inside of node-ipfsd-ctl.  Yay static binaries!
- [ ] Wrap that in an [Electron](http://github.com/atom/electron) app that spawns a daemon for the lifetime of the app, and can show an app window with the webui.

**Comment by jbenet** [comment]
cc @krl

**Comment by whyrusleeping** [comment]
I want to give this rather high priority, it will help adoption significantly

**Comment by bcomnes** [comment]
Looks like @krl handled it! https://github.com/ipfs/electron-app

**Comment by daviddias** [comment]
There is so much more that I thought it would be good to give an update here https://github.com/ipfs-shipyard/ipfs-desktop#ipfs-desktop
