### ISSUE TITLE
Prose writes static web content to Github (so it could probably write to IPFS too)

### ISSUE THREAD

**Issue by jbshirk** [ipfs/notes#87]
[How We Build CMS-Free Websites](https://developmentseed.org/blog/2012/07/27/build-cms-free-websites/)
Prose.io and Jekyll enable building simple, flexible, and reliable without the overhead of dynamic CMSs

> "To that end we’re investing heavily in Prose.io, a web-based content editor specifically designed to work well with Jekyll. Prose allows for editing text files hosted in GitHub, where we store all of our code. It provides an elegant interface that focuses on writing. Content producers can go to Prose.io to create new posts or edit existing ones through this simple interface. Their changes are saved directly to GitHub, which maintains a record of every version of every file. With GitHub Pages enabled, we can host Jekyll sites for free directly from the code we commit to GitHub. Changes made through Prose on a GitHub Pages site are automatically pushed live to the site. Or, the code edited with Prose can be copied from GitHub to any other hosting environment."

**Comment by jbenet** [comment]
Indeed! we should make a list of all CMS-like things that produce static sites

**Comment by jbshirk** [comment]
@jbenet  Created new thread for this purpose.
