### ISSUE TITLE
"screenshot upload to ipfs and copy link to clipboard" project

### ISSUE THREAD

**Issue by jbshirk** [ipfs/notes#88]
can anyone tell me the name of the app or project mentioned @ 29:20 that does "screenshot upload to ipfs and copy link to clipboard" ?
Redistributing the Web with IPFS - BattleMeshV8
https://youtu.be/OAkJAPS5yoQ?t=29m20s

**Comment by diasdavid** [comment]
@jbshirk this one https://github.com/jbenet/ipfs-screencap ?

https://github.com/ipfs/station will also be able to do this:)

**Comment by jbshirk** [comment]
Thank you!
